version: "3.8"

services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=bois_de_morchene
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - sameNetworkAsMysql
    ports:
      - 3307:3306

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - sameNetworkAsMysql
    depends_on:
      - db

  frontend:
    restart: on-failure
    build:
      context: ./front
    ports:
      - 3001:3000
    networks:
      - sameNetworkAsMysql
    depends_on:
      - api

networks:
  sameNetworkAsMysql:
    driver: bridge